### ISSUE TITLE
Does this run on TempleOS

### ISSUE THREAD

**Issue by uniboi** [F1F7Y/Fifty.InfiniteLoadouts#1]
First

**Comment by BimNoah** [comment]
Had issues running it on RedStarOS, would love for a bigger spectrum of supported Operating Systems (b'-')b

**Comment by uniboi** [comment]
![image](https://user-images.githubusercontent.com/64006268/180858209-e56cb660-e749-43ea-a282-df1e2016dca6.png)
@F1F7Y I get this error when I try to run this please fix thanks
also, is the masterserver down? .status

**Comment by BimNoah** [comment]
If you want to test it on RedStarOS for yourself, consider installing it on a bare-metal system. 
But remember, make sure to connect it to the internet to download this mod
Here's a link for you if you choose to get to the root of this problem (b'-')b

https://archiveos.org/redstar/

**Comment by F1F7Y** [comment]
bruh

**Comment by F1F7Y** [comment]
The germans invaded again :(

**Comment by uniboi** [comment]
I fixed it by deleting System32
